services: 
  django-web:
    build: .
    container_name: django-docker
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      PIPELINE: ${PIPELINE}
      HOST_URL: ${HOST_URL}
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    env_file: ".env"
    networks:
      - frontend

  nginx:
      image: nginx:1.23-alpine
      env_file: .env
      restart: unless-stopped
      volumes:
        - type: volume
          source: media
          target: /usr/share/nginx/html/media
          read_only: true
          volume:
            nocopy: true
        - type: volume
          source: staticfiles
          target: /usr/share/nginx/html/static
          read_only: true
          volume:
            nocopy: true
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - django-web
      networks:
        - frontend
      labels:
        - traefik.enable=true
        - traefik.http.routers.staticfiles.rule=Host(`your.domain.here`)
        - traefik.http.routers.staticfiles.entrypoints=websecure
        - traefik.http.routers.staticfiles.tls=true
        - traefik.http.routers.staticfiles.tls.certresolver=production


volumes:
  staticfiles:
  media:

networks:
  frontend:
    external: true